# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=2)),
                ('birth_date', models.DateField()),
                ('birth_province', models.SmallIntegerField(choices=[(1, '北京'), (2, '天津'), (3, '上海'), (4, '重庆'), (5, '河北'), (6, '河南'), (7, '云南'), (8, '辽宁'), (9, '黑龙江'), (10, '湖南'), (11, '安徽'), (12, '山东'), (13, '新疆'), (14, '江苏'), (15, '河北'), (16, '广西'), (17, '甘肃'), (18, '山西'), (19, '内蒙古'), (20, '陕西'), (21, '吉林'), (22, '福建'), (23, '贵州'), (24, '广东'), (25, '青海'), (26, '西藏'), (27, '宁夏'), (28, '海南'), (29, '台湾'), (30, '香港'), (31, '澳门')], default=1)),
                ('avatar', models.URLField(blank=True, default='', max_length=255)),
                ('grade', models.SmallIntegerField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=140, null=True)),
            ],
            options={
                'db_table': 'auth_childProfile',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('relationship', models.SmallIntegerField(choices=[(1, '爸爸'), (2, '妈妈'), (3, '爷爷'), (4, '奶奶'), (5, '家长')], default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parentProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_parentProfile',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('subject', models.SmallIntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语'), (4, '生物'), (5, '物理'), (6, '化学'), (7, '历史'), (8, '地理'), (9, '政治')], default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacherProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_teacherProfile',
            },
        ),
    ]
