# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalizedLearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('relationship', models.SmallIntegerField(choices=[(1, '爸爸'), (2, '妈妈'), (3, '爷爷'), (4, '奶奶'), (5, '家长')], default=2)),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=2)),
                ('birth_date', models.DateField()),
                ('birth_province', models.SmallIntegerField(choices=[(1, '北京'), (2, '天津'), (3, '上海'), (4, '重庆'), (5, '河北'), (6, '河南'), (7, '云南'), (8, '辽宁'), (9, '黑龙江'), (10, '湖南'), (11, '安徽'), (12, '山东'), (13, '新疆'), (14, '江苏'), (15, '河北'), (16, '广西'), (17, '甘肃'), (18, '山西'), (19, '内蒙古'), (20, '陕西'), (21, '吉林'), (22, '福建'), (23, '贵州'), (24, '广东'), (25, '青海'), (26, '西藏'), (27, '宁夏'), (28, '海南'), (29, '台湾'), (30, '香港'), (31, '澳门')], default=1)),
                ('avatar', models.URLField(blank=True, default='', max_length=255)),
                ('grade', models.SmallIntegerField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=140)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('school', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ManyToManyField(related_name='study_class', to='personalizedLearning.Student')),
            ],
            options={
                'db_table': 'study_class',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('subject', models.SmallIntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语'), (4, '生物'), (5, '物理'), (6, '化学'), (7, '历史'), (8, '地理'), (9, '政治')], default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.DeleteModel(
            name='ChildProfile',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.AddField(
            model_name='studyclass',
            name='teacher',
            field=models.ManyToManyField(related_name='study_class', to='personalizedLearning.Teacher'),
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(related_name='parent', to='personalizedLearning.Student'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
